{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "resources": [
    "../../../infrastructure/cilium"
  ],
  "configMapGenerator": [
    {
      "name": "cilium-values",
      "namespace": "kube-system",
      "behavior": "replace",
      "files": [
        "values.yaml"
      ]
    }
  ],
  "generatorOptions": {
    "disableNameSuffixHash": true,
    "labels": {
      "reconcile.fluxcd.io/watch": "Enabled"
    }
  }
}
