{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "resources": [
    "../../../infrastructure/network"
  ],
  "patches": [
    {
      "target": {
        "kind": "GatewayClass",
        "name": "cilium"
      },
      "patch": "[{\"op\": \"replace\", \"path\": \"/spec/controllerName\", \"value\": \"traefik.io/gateway-controller\"}]"
    }
  ]
}
