apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    # Longhorn needs privileged pods and host mounts for its V1 engine and CSI.
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: garage
---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
